<?php

namespace App\Http\Controllers;

use App\Models\Countie;
use Illuminate\Http\Request;

class CountiesController extends Controller
{
    public function create()
    {
        $data = [
            'BARINGO'         => 'Baringo County',
            'BOMET'           => 'Bomet County',
            'BUNGOMA'         => 'Bungoma County',
            'BUSIA'           => 'Busia County',
            'ELGEYO-MARAKWET' => 'Elgeyo-Marakwet County',
            'EMBU'            => 'Embu County',
            'GARISSA'         => 'Garissa County',
            'HOMA-BAY'        => 'Homa-bay County',
            'ISIOLO'          => 'Isiolo County',
            'KAJIADO'         => 'Kajiado County',
            'KAKAMEGA'        => 'Kakamega County',
            'KERICHO'         => 'Kericho County',
            'KIAMBU'          => 'Kiambu County',
            'KILIFI'          => 'Kilifi County',
            'KIRINYAGA'       => 'Kirinyaga County',
            'KISII'           => 'Kisii County',
            'KISUMU'          => 'Kisumu County',
            'KITUI'           => 'Kitui County',
            'KWALE'           => 'Kwale County',
            'LAIKIPIA'        => 'Laikipia County',
            'LAMU'            => 'Lamu County',
            'MACHAKOS'        => 'Machakos County',
            'MAKUENI'         => 'Makueni County',
            'MANDERA'         => 'Mandera County',
            'MARSABIT'        => 'Marsabit County',
            'MERU'            => 'Meru County',
            'MIGORI'          => 'Migori County',
            'MOMBASA'         => 'Mombasa County',
            'MURANGA'         => 'Muranga County',
            'NAIROBI'         => 'Nairobi County',
            'NAKURU'          => 'Nakuru County',
            'NANDI'           => 'Nandi County',
            'NAROK'           => 'Narok County',
            'NYAMIRA'         => 'Nyamira County',
            'NYANDARUA'       => 'Nyandarua County',
            'NYERI'           => 'Nyeri County',
            'SAMBURU'         => 'Samburu County',
            'SIAYA'           => 'Siaya County',
            'TAITA-TAVETA'    => 'Taita-Taveta County',
            'TANA RIVER'      => 'Tana River County',
            'THARAKA-NITHI'   => 'Tharaka-Nithi County',
            'TRANS-NZOIA'     => 'Trans-Nzoia County',
            'TURKANA'         => 'Turkana County',
            'UASIN GISHU'     => 'Uasin Gishu County',
            'VIHIGA'          => 'Vihiga County',
            'WAJIR'           => 'Wajir County',
            'WEST POKOT'      => 'West Pokot County',
        ];



        $countries = [
            '"iso" : "AF", "country" : "Afghanistan"',
            '"iso" : "AL", "country" : "Albania"',
            '"iso" : "DZ", "country" : "Algeria"',
            '"iso" : "AS", "country" : "American Samoa"',
            '"iso" : "AD", "country" : "Andorra"',
            '"iso" : "AO", "country" : "Angola"',
            '"iso" : "AI", "country" : "Anguilla"',
            '"iso" : "AQ", "country" : "Antarctica"',
            '"iso" : "AG", "country" : "Antigua and Barbuda"',
            '"iso" : "AR", "country" : "Argentina"',
            '"iso" : "AM", "country" : "Armenia"',
            '"iso" : "AW", "country" : "Aruba"',
            '"iso" : "AU", "country" : "Australia"',
            '"iso" : "AT", "country" : "Austria"',
            '"iso" : "AZ", "country" : "Azerbaijan"',
            '"iso" : "BS", "country" : "Bahamas"',
            '"iso" : "BH", "country" : "Bahrain"',
            '"iso" : "BD", "country" : "Bangladesh"',
            '"iso" : "BB", "country" : "Barbados"',
            '"iso" : "BY", "country" : "Belarus"',
            '"iso" : "BE", "country" : "Belgium"',
            '"iso" : "BZ", "country" : "Belize"',
            '"iso" : "BJ", "country" : "Benin"',
            '"iso" : "BM", "country" : "Bermuda"',
            '"iso" : "BT", "country" : "Bhutan"',
            '"iso" : "BO", "country" : "Bolivia"',
            '"iso" : "BA", "country" : "Bosnia and Herzegovina"',
            '"iso" : "BW", "country" : "Botswana"',
            '"iso" : "BV", "country" : "Bouvet Island"',
            '"iso" : "BR", "country" : "Brazil"',
            '"iso" : "IO", "country" : "British Indian Ocean Territory"',
            '"iso" : "BN", "country" : "Brunei Darussalam"',
            '"iso" : "BG", "country" : "Bulgaria"',
            '"iso" : "BF", "country" : "Burkina Faso"',
            '"iso" : "BI", "country" : "Burundi"',
            '"iso" : "KH", "country" : "Cambodia"',
            '"iso" : "CM", "country" : "Cameroon"',
            '"iso" : "CA", "country" : "Canada"',
            '"iso" : "CV", "country" : "Cape Verde"',
            '"iso" : "KY", "country" : "Cayman Islands"',
            '"iso" : "CF", "country" : "Central African Republic"',
            '"iso" : "TD", "country" : "Chad"',
            '"iso" : "CL", "country" : "Chile"',
            '"iso" : "CN", "country" : "China"',
            '"iso" : "CX", "country" : "Christmas Island"',
            '"iso" : "CC", "country" : "Cocos (Keeling) Islands"',
            '"iso" : "CO", "country" : "Colombia"',
            '"iso" : "KM", "country" : "Comoros"',
            '"iso" : "CG", "country" : "Congo"',
            '"iso" : "CD", "country" : "Congo, the Democratic Republic of the"',
            '"iso" : "CK", "country" : "Cook Islands"',
            '"iso" : "CR", "country" : "Costa Rica"',
            '"iso" : "CI", "country" : "Cote D`Ivoire"',
            '"iso" : "HR", "country" : "Croatia"',
            '"iso" : "CU", "country" : "Cuba"',
            '"iso" : "CY", "country" : "Cyprus"',
            '"iso" : "CZ", "country" : "Czech Republic"',
            '"iso" : "DK", "country" : "Denmark"',
            '"iso" : "DJ", "country" : "Djibouti"',
            '"iso" : "DM", "country" : "Dominica"',
            '"iso" : "DO", "country" : "Dominican Republic"',
            '"iso" : "EC", "country" : "Ecuador"',
            '"iso" : "EG", "country" : "Egypt"',
            '"iso" : "SV", "country" : "El Salvador"',
            '"iso" : "GQ", "country" : "Equatorial Guinea"',
            '"iso" : "ER", "country" : "Eritrea"',
            '"iso" : "EE", "country" : "Estonia"',
            '"iso" : "ET", "country" : "Ethiopia"',
            '"iso" : "FK", "country" : "Falkland Islands (Malvinas)"',
            '"iso" : "FO", "country" : "Faroe Islands"',
            '"iso" : "FJ", "country" : "Fiji"',
            '"iso" : "FI", "country" : "Finland"',
            '"iso" : "FR", "country" : "France"',
            '"iso" : "GF", "country" : "French Guiana"',
            '"iso" : "PF", "country" : "French Polynesia"',
            '"iso" : "TF", "country" : "French Southern Territories"',
            '"iso" : "GA", "country" : "Gabon"',
            '"iso" : "GM", "country" : "Gambia"',
            '"iso" : "GE", "country" : "Georgia"',
            '"iso" : "DE", "country" : "Germany"',
            '"iso" : "GH", "country" : "Ghana"',
            '"iso" : "GI", "country" : "Gibraltar"',
            '"iso" : "GR", "country" : "Greece"',
            '"iso" : "GL", "country" : "Greenland"',
            '"iso" : "GD", "country" : "Grenada"',
            '"iso" : "GP", "country" : "Guadeloupe"',
            '"iso" : "GU", "country" : "Guam"',
            '"iso" : "GT", "country" : "Guatemala"',
            '"iso" : "GN", "country" : "Guinea"',
            '"iso" : "GW", "country" : "Guinea-Bissau"',
            '"iso" : "GY", "country" : "Guyana"',
            '"iso" : "HT", "country" : "Haiti"',
            '"iso" : "HM", "country" : "Heard Island and Mcdonald Islands"',
            '"iso" : "VA", "country" : "Holy See (Vatican City State)"',
            '"iso" : "HN", "country" : "Honduras"',
            '"iso" : "HK", "country" : "Hong Kong"',
            '"iso" : "HU", "country" : "Hungary"',
            '"iso" : "IS", "country" : "Iceland"',
            '"iso" : "IN", "country" : "India"',
            '"iso" : "ID", "country" : "Indonesia"',
            '"iso" : "IR", "country" : "Iran, Islamic Republic of"',
            '"iso" : "IQ", "country" : "Iraq"',
            '"iso" : "IE", "country" : "Ireland"',
            '"iso" : "IL", "country" : "Israel"',
            '"iso" : "IT", "country" : "Italy"',
            '"iso" : "JM", "country" : "Jamaica"',
            '"iso" : "JP", "country" : "Japan"',
            '"iso" : "JO", "country" : "Jordan"',
            '"iso" : "KZ", "country" : "Kazakhstan"',
            '"iso" : "KE", "country" : "Kenya"',
            '"iso" : "KI", "country" : "Kiribati"',
            '"iso" : "KP", "country" : "Korea, Democratic People`s Republic of"',
            '"iso" : "KR", "country" : "Korea, Republic of"',
            '"iso" : "KW", "country" : "Kuwait"',
            '"iso" : "KG", "country" : "Kyrgyzstan"',
            '"iso" : "LA", "country" : "Lao People`s Democratic Republic"',
            '"iso" : "LV", "country" : "Latvia"',
            '"iso" : "LB", "country" : "Lebanon"',
            '"iso" : "LS", "country" : "Lesotho"',
            '"iso" : "LR", "country" : "Liberia"',
            '"iso" : "LY", "country" : "Libyan Arab Jamahiriya"',
            '"iso" : "LI", "country" : "Liechtenstein"',
            '"iso" : "LT", "country" : "Lithuania"',
            '"iso" : "LU", "country" : "Luxembourg"',
            '"iso" : "MO", "country" : "Macao"',
            '"iso" : "MK", "country" : "Macedonia, the Former Yugoslav Republic of"',
            '"iso" : "MG", "country" : "Madagascar"',
            '"iso" : "MW", "country" : "Malawi"',
            '"iso" : "MY", "country" : "Malaysia"',
            '"iso" : "MV", "country" : "Maldives"',
            '"iso" : "ML", "country" : "Mali"',
            '"iso" : "MT", "country" : "Malta"',
            '"iso" : "MH", "country" : "Marshall Islands"',
            '"iso" : "MQ", "country" : "Martinique"',
            '"iso" : "MR", "country" : "Mauritania"',
            '"iso" : "MU", "country" : "Mauritius"',
            '"iso" : "YT", "country" : "Mayotte"',
            '"iso" : "MX", "country" : "Mexico"',
            '"iso" : "FM", "country" : "Micronesia, Federated States of"',
            '"iso" : "MD", "country" : "Moldova, Republic of"',
            '"iso" : "MC", "country" : "Monaco"',
            '"iso" : "MN", "country" : "Mongolia"',
            '"iso" : "MS", "country" : "Montserrat"',
            '"iso" : "MA", "country" : "Morocco"',
            '"iso" : "MZ", "country" : "Mozambique"',
            '"iso" : "MM", "country" : "Myanmar"',
            '"iso" : "NA", "country" : "Namibia"',
            '"iso" : "NR", "country" : "Nauru"',
            '"iso" : "NP", "country" : "Nepal"',
            '"iso" : "NL", "country" : "Netherlands"',
            '"iso" : "AN", "country" : "Netherlands Antilles"',
            '"iso" : "NC", "country" : "New Caledonia"',
            '"iso" : "NZ", "country" : "New Zealand"',
            '"iso" : "NI", "country" : "Nicaragua"',
            '"iso" : "NE", "country" : "Niger"',
            '"iso" : "NG", "country" : "Nigeria"',
            '"iso" : "NU", "country" : "Niue"',
            '"iso" : "NF", "country" : "Norfolk Island"',
            '"iso" : "MP", "country" : "Northern Mariana Islands"',
            '"iso" : "NO", "country" : "Norway"',
            '"iso" : "OM", "country" : "Oman"',
            '"iso" : "PK", "country" : "Pakistan"',
            '"iso" : "PW", "country" : "Palau"',
            '"iso" : "PS", "country" : "Palestinian Territory, Occupied"',
            '"iso" : "PA", "country" : "Panama"',
            '"iso" : "PG", "country" : "Papua New Guinea"',
            '"iso" : "PY", "country" : "Paraguay"',
            '"iso" : "PE", "country" : "Peru"',
            '"iso" : "PH", "country" : "Philippines"',
            '"iso" : "PN", "country" : "Pitcairn"',
            '"iso" : "PL", "country" : "Poland"',
            '"iso" : "PT", "country" : "Portugal"',
            '"iso" : "PR", "country" : "Puerto Rico"',
            '"iso" : "QA", "country" : "Qatar"',
            '"iso" : "RE", "country" : "Reunion"',
            '"iso" : "RO", "country" : "Romania"',
            '"iso" : "RU", "country" : "Russian Federation"',
            '"iso" : "RW", "country" : "Rwanda"',
            '"iso" : "SH", "country" : "Saint Helena"',
            '"iso" : "KN", "country" : "Saint Kitts and Nevis"',
            '"iso" : "LC", "country" : "Saint Lucia"',
            '"iso" : "PM", "country" : "Saint Pierre and Miquelon"',
            '"iso" : "VC", "country" : "Saint Vincent and the Grenadines"',
            '"iso" : "WS", "country" : "Samoa"',
            '"iso" : "SM", "country" : "San Marino"',
            '"iso" : "ST", "country" : "Sao Tome and Principe"',
            '"iso" : "SA", "country" : "Saudi Arabia"',
            '"iso" : "SN", "country" : "Senegal"',
            '"iso" : "CS", "country" : "Serbia and Montenegro"',
            '"iso" : "SC", "country" : "Seychelles"',
            '"iso" : "SL", "country" : "Sierra Leone"',
            '"iso" : "SG", "country" : "Singapore"',
            '"iso" : "SK", "country" : "Slovakia"',
            '"iso" : "SI", "country" : "Slovenia"',
            '"iso" : "SB", "country" : "Solomon Islands"',
            '"iso" : "SO", "country" : "Somalia"',
            '"iso" : "ZA", "country" : "South Africa"',
            '"iso" : "GS", "country" : "South Georgia and the South Sandwich Islands"',
            '"iso" : "ES", "country" : "Spain"',
            '"iso" : "LK", "country" : "Sri Lanka"',
            '"iso" : "SD", "country" : "Sudan"',
            '"iso" : "SR", "country" : "Suriname"',
            '"iso" : "SJ", "country" : "Svalbard and Jan Mayen"',
            '"iso" : "SZ", "country" : "Swaziland"',
            '"iso" : "SE", "country" : "Sweden"',
            '"iso" : "CH", "country" : "Switzerland"',
            '"iso" : "SY", "country" : "Syrian Arab Republic"',
            '"iso" : "TW", "country" : "Taiwan, Province of China"',
            '"iso" : "TJ", "country" : "Tajikistan"',
            '"iso" : "TZ", "country" : "Tanzania, United Republic of"',
            '"iso" : "TH", "country" : "Thailand"',
            '"iso" : "TL", "country" : "Timor-Leste"',
            '"iso" : "TG", "country" : "Togo"',
            '"iso" : "TK", "country" : "Tokelau"',
            '"iso" : "TO", "country" : "Tonga"',
            '"iso" : "TT", "country" : "Trinidad and Tobago"',
            '"iso" : "TN", "country" : "Tunisia"',
            '"iso" : "TR", "country" : "Turkey"',
            '"iso" : "TM", "country" : "Turkmenistan"',
            '"iso" : "TC", "country" : "Turks and Caicos Islands"',
            '"iso" : "TV", "country" : "Tuvalu"',
            '"iso" : "UG", "country" : "Uganda"',
            '"iso" : "UA", "country" : "Ukraine"',
            '"iso" : "AE", "country" : "United Arab Emirates"',
            '"iso" : "GB", "country" : "United Kingdom"',
            '"iso" : "US", "country" : "United States"',
            '"iso" : "UM", "country" : "United States Minor Outlying Islands"',
            '"iso" : "UY", "country" : "Uruguay"',
            '"iso" : "UZ", "country" : "Uzbekistan"',
            '"iso" : "VU", "country" : "Vanuatu"',
            '"iso" : "VE", "country" : "Venezuela"',
            '"iso" : "VN", "country" : "Viet Nam"',
            '"iso" : "VG", "country" : "Virgin Islands, British"',
            '"iso" : "VI", "country" : "Virgin Islands, U.s."',
            '"iso" : "WF", "country" : "Wallis and Futuna"',
            '"iso" : "EH", "country" : "Western Sahara"',
            '"iso" : "YE", "country" : "Yemen"',
            '"iso" : "ZM", "country" : "Zambia"',
            '"iso" : "ZW", "country" : "Zimbabwe"'

        ];



        foreach ($countries as $country) {
            // $data_item['name'] = $county;
            // Countie::create($data_item);
            dd($country('iso'));
        }
        // Countie::create($formFields);
    }
}
