<?php
#############################################################
#                   47 counties of Kenya                    #
#############################################################
$config['counties'] = [
  'BARINGO'         => 'Baringo County',
  'BOMET'           => 'Bomet County',
  'BUNGOMA'         => 'Bungoma County',
  'BUSIA'           => 'Busia County',
  'ELGEYO-MARAKWET' => 'Elgeyo-Marakwet County',
  'EMBU'            => 'Embu County',
  'GARISSA'         => 'Garissa County',
  'HOMA-BAY'        => 'Homa-bay County',
  'ISIOLO'          => 'Isiolo County',
  'KAJIADO'         => 'Kajiado County',
  'KAKAMEGA'        => 'Kakamega County',
  'KERICHO'         => 'Kericho County',
  'KIAMBU'          => 'Kiambu County',
  'KILIFI'          => 'Kilifi County',
  'KIRINYAGA'       => 'Kirinyaga County',
  'KISII'           => 'Kisii County',
  'KISUMU'          => 'Kisumu County',
  'KITUI'           => 'Kitui County',
  'KWALE'           => 'Kwale County',
  'LAIKIPIA'        => 'Laikipia County',
  'LAMU'            => 'Lamu County',
  'MACHAKOS'        => 'Machakos County',
  'MAKUENI'         => 'Makueni County',
  'MANDERA'         => 'Mandera County',
  'MARSABIT'        => 'Marsabit County',
  'MERU'            => 'Meru County',
  'MIGORI'          => 'Migori County',
  'MOMBASA'         => 'Mombasa County',
  'MURANGA'         => 'Muranga County',
  'NAIROBI'         => 'Nairobi County',
  'NAKURU'          => 'Nakuru County',
  'NANDI'           => 'Nandi County',
  'NAROK'           => 'Narok County',
  'NYAMIRA'         => 'Nyamira County',
  'NYANDARUA'       => 'Nyandarua County',
  'NYERI'           => 'Nyeri County',
  'SAMBURU'         => 'Samburu County',
  'SIAYA'           => 'Siaya County',
  'TAITA-TAVETA'    => 'Taita-Taveta County',
  'TANA RIVER'      => 'Tana River County',
  'THARAKA-NITHI'   => 'Tharaka-Nithi County',
  'TRANS-NZOIA'     => 'Trans-Nzoia County',
  'TURKANA'         => 'Turkana County',
  'UASIN GISHU'     => 'Uasin Gishu County',
  'VIHIGA'          => 'Vihiga County',
  'WAJIR'           => 'Wajir County',
  'WEST POKOT'      => 'West Pokot County',
];
